### ISSUE TITLE
How to maintain future AWE parity?

### ISSUE THREAD

**Issue by stubkan** [Asy93/AWE-Grunker-s-Finest#6]
The posts I wrote about this on the discord appear to have been ignored or missed so I'll write this issue here.

The issue is - what happens when AWE gets a new gun or new things...  How do we get them in here?

If this repository was a fork of the AWE repository then it would simply be a case of pressing a button to pull upstream changes.  

This would not overwrite Grunker changes which can easily be maintained, and be far simpler than having to manually find and download all the new files or changes in text files and painstakingly insert them into this repository and making sure they dont overwrite Grunker changes (which github would be doing automatically if this was a fork)

**Comment by CaptainPicarl** [comment]
It's a simple matter of Aryx coming in, creating a commit and associated pull request specifically for new stuff, and having SW Devs check the diffs before merging. 

You don't necessarily want to straight-fork the OG AWE repo for our branch, because changes in the SW repo may be overwritten by the Aryx repo by a PR. In the future: If Aryx releases a new weapon - it would be possible for her to swing by, drop the new files into a new fork of _our_ branch, and then have SW devs check the changes to make identify conflicts. Should be a much smaller amount of things that could break, though there's always the occasion that something on the AWE-side gets forgotten and needs hot-inserted.

Anyways, The setup they have now seems fine.

**Comment by stubkan** [comment]
Sounds like the exact same situation we have now, which led to the creation of this github.  Ie, we cant do nothing until Aryx decides to.  

Aryx fixed jack o lasers more than a month before getting around to fixing it for Grunkers after people were constantly on their case about it.  If this github was a fork, we could have had jack o lasers fixed the day after AWE was fixed, and Aryx would have had to do nothing.  Which, again, was the whole reason behind asking for control over the mod.

A fork is never going to be a straight copy as long as we have our own changes in it, which is why forks exist.  We'd only have to upload Grunkers changes once, and then in future all upstream bug fixes, additions etc will be merged and maintain Grunker change integrity.

It will be faaaaaaar easier on everyone to do it the way that github was designed for.

**Comment by CaptainPicarl** [comment]
It's not the exact same situation we had prior. If it was - we wouldn't be discussing what changes to make on our own branch via issues.

Anyways, What you described in this: 
"A fork is never going to be a straight copy as long as we have our own changes in it, which is why forks exist. We'd only have to upload Grunkers changes once, and then in future all upstream bug fixes, additions etc will be merged and maintain Grunker change integrity."

...Is pretty much moot, per Asy's comment that the Aryx branch is going away anyways. That's besides the point that we aren't technically a fork, since we won't have some upstream to pull from.  So, like: Yes - forking and modifying on our end would be an easy way to pull Aryx changes...but not only was that _not_ how this repo was setup initially: It doesn't appear that Aryx is going to be accessible to us via Github at all. 

And as far as "Unable to do anything until Aryx decides to":
We were always in that boat. We were always _going to be in that boat._
We're able to change and fiddle with stuff, but in our current environment: We'll always be tethered to working with Aryx to get new PR's.
